name: Security checks (Gitleaks + Semgrep)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  secrets-and-sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go (for gitleaks)
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash -s -- -b /usr/local/bin
          gitleaks version
      - name: Run gitleaks (repo)
        run: |
          gitleaks detect --no-banner --verbose --report-format sarif --report-path gitleaks.sarif || true
      - name: Upload gitleaks SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep
      - name: Run Semgrep
        run: |
          semgrep --config auto . --json -o semgrep.json --disable-version-check || true
      - name: Upload Semgrep JSON as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep.json
          path: semgrep.json
