name: Security checks (Gitleaks + Semgrep)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  secrets-and-sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Gitleaks with retry (install via Go) + run
      - name: Setup Go for gitleaks
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install gitleaks (via go install)
        run: |
          go install github.com/zricethezav/gitleaks/v8@v8.24.3
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          gitleaks version
      - name: Run gitleaks with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: gitleaks detect --no-banner --redact --report-format sarif --report-path gitleaks.sarif --config .gitleaks.toml
      - name: Upload gitleaks SARIF
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      # Semgrep (SARIF for Code Scanning) with retry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
      - name: Run Semgrep (SARIF) with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            semgrep --version
            semgrep --config auto . --sarif -o semgrep.sarif --disable-version-check
      - name: Upload Semgrep SARIF
        if: always() && hashFiles('semgrep.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
